### ISSUE TITLE
Ensure testing for checks that look up types works properly

### ISSUE THREAD

**Issue by jlmaddox** [paninij/paninij#143]
The following methods used for different checks uses type look ups. We need to ensure that they are being tested correctly since the type look ups have various possible states at different times.

- `org.paninij.proc.check.template.NoLocalSignatureCheck#checkLocalField()`
- `org.paninij.proc.check.capsule.FieldsCheck#seemsToBeCapsuleField()`

**Comment by dwtj** [comment]
To clarify the purpose of this testing and the potential problem, here is a relevant comment from `FieldsCheck#seemsToBeCapsuleField()`:

```
When the field's type kind is `ERROR` it means that we cannot retrieve a field's
fully qualified type. This is either because the user has has incorrectly used some
unavailable type or (more likely) the field's type has not yet been generated by
`proc`. Here we just assume that all such fields are of capsule type.
```

The issue is that we are not being very smart about the case where we are performing a check during annotation processing on some class which *uses* a type which has not yet been created by the annotation processor. Ideally we'd do something smart to get out of this circularity, but until then we need testing.
